helsingborg-stad/styleguide

source/js/app.js
source/js/modal.js
source/sass/component/_modal.scss
views/layout/master.blade.php
views/pages/component/modal.blade.php

- Add Javascript for modal
- Add styling

Modal functionality

---

views/pages/component/icon.blade.php

Icon Component

---

source/sass/component/_typography.scss
source/sass/main.scss
views/pages/component/typography.blade.php

- Add Example
- Add Styling
- Add Include in main css file

Typography Component

---

source/sass/component/fab.scss
source/sass/main.scss
views/pages/component/fab.blade.php

Floating Action Button

---

source/js/modal.js
source/sass/component/_image.scss
source/sass/component/_modal.scss
source/sass/generic/_icons.scss
views/pages/component/modal.blade.php

- Add supoort for class list
- Add corrected structure

Modal Resctrucure

---

source/js/toggle.js
source/sass/component/_avatar.scss
source/sass/component/_button.scss
source/sass/component/_buttonGroup.scss
source/sass/component/_dropdown.scss
source/sass/element/_list.scss
source/sass/main.scss
source/sass/mixin/_button.scss
source/sass/setting/_var_colors.scss
source/sass/setting/_var_fonts.scss
views/pages/component/button.blade.php
views/pages/component/buttonGroup.blade.php
views/pages/component/dropdown.blade.php

Add a new component for dropdown.
- Select direction in which the popup-menu opens
- Popup on hover or click
- Slot contains buttons
Add new design for buttons
Make buttons toggle by adding toggle true
Make button groups toggle by adding toggle true and by adding js-toggle-trigger

Dropdown, Toggle, design buttons

---

source/js/app.js
source/js/dropdown.js
source/js/splitButton.js
source/sass/component/_buttonGroup.scss
source/sass/component/_dropdown.scss
views/pages/component/buttonGroup.blade.php
views/pages/component/splitbutton.blade.php
views/pages/component/usage/splitbutton.blade.php

Simply a collection of components that creates a
splitbutton. Namely a buttongroup with a button and
a dropdown that are synced so that when you choose an
item in the list the buttons text changes to that of the
chosen item.

Splitbutton

---

source/sass/component/_button.scss
views/pages/component/button.blade.php

New color fill for outline buttons on toggle.
New examples and parameter documentation.

Outline toggle only

---

source/js/menu.js
source/sass/component/_navbar.scss

- Add min size
- Add corrected styling
- Add new layout to dom build

Navbar Accessability

---

source/sass/component/_card.scss
views/pages/component/card.blade.php
views/pages/component/usage/card.blade.php

Card - accordions

---

.stylelintignore
source/js/menu.js
source/sass/component/_navbar.scss
views/pages/component/navbar.blade.php
webpack.config.js

- Add new design on desktop
- Add animation on mobile accordion
- Add scss lint ignore

Navbar - Desktop Design

---

source/sass/generic/_load-animation.scss
source/sass/main.scss
source/sass/mixin/animations/_fade-in.scss

- Add mixin for fade
- Add class for fade in on load
- Add includes to main

Animation On Load

---

source/js/menu.js
source/sass/component/_accordion.scss
source/sass/component/_breadcrumb.scss
views/pages/component/card.blade.php
views/pages/component/dropdown.blade.php
views/pages/component/icon.blade.php
views/pages/component/notice.blade.php
views/pages/component/splitbutton.blade.php
views/pages/icons.blade.php

- Add correct icons
- Add correct icon in js

Broken Icons

---

source/sass/component/_navbar.scss

Navbar Accesability

---

source/sass/component/_modal.scss

- Add css to handle overflow with scroll

Modal - Overflow

---

source/sass/component/_card.scss
source/sass/setting/_var_colors.scss
views/pages/component/card.blade.php

Card - Dark background

---

source/js/toggle.js
source/sass/component/_button.scss
source/sass/mixin/_button.scss
source/sass/setting/_var_colors.scss
views/layout/doc.blade.php
views/pages/component/usage/button/disabled.blade.php
views/pages/component/usage/button/text.blade.php

Fix broken toggle buttons,
colors and doc button icon,
fix examples

Button fix

---

source/js/app.js
source/js/menu.js

- Add much more documentation
- Add following of rules

Navbar Script - Refactor

---

source/sass/component/_button.scss
source/sass/setting/_var_colors.scss
views/pages/component/usage/card/buttons.blade.php
views/pages/component/usage/card/slots.blade.php

Fix buttons that followed the old way
of configuring buttons.

Card doc button fix

---

assets/data/eventsDummyData.json
source/js/app.js
source/js/calendar-javascript-lib.js
source/js/calendar.js
source/js/modal.js
source/sass/component/_calendar.scss
source/sass/main.scss
views/pages/component/molecules/modal.blade.php
views/pages/component/organisms/calendar.blade.php
views/pages/component/usage/calendar/calendar.blade.php
views/pages/component/usage/calendar/calendar.json

Modify calendar-js-lib to fetch events from url
and display them as either available or booked
in a modal.
- Available
- Checkboxes for each aviable slot and button to post timestamps
- Booked
- Show timeslots that have been booked

Calendar component

---

source/php/Helper/Documentation.php

- add json based order
- add descriptive error

Documentation

---

source/sass/component/_button.scss
source/sass/setting/_var_colors.scss
views/pages/component/usage/button/button.json

New colors, box-shadow only on filled type.
New hover and active colors.

Button design

---

source/sass/utility/_border-radius.scss
source/sass/utility/_border.scss
source/sass/utility/_color.scss
views/docs/utility/Border-radius/Border-radius.json
views/docs/utility/colors/Colors__bg.json
views/docs/utility/colors/Colors__text.json

- add more colors
- add corrected sides
- add defaults
- add corrected naming
- add new values to json

Utilities Improvements

---

views/layout/doc.blade.php
views/pages/components/atoms/loader.blade.php
views/pages/components/usage/loader/color.blade.php
views/pages/components/usage/loader/loader.json
views/pages/components/usage/loader/shape.blade.php
views/pages/components/usage/loader/size.blade.php

Utilize new doc structure for loaders.

Loader usage doc

---

source/sass/function/_string-replace.scss
source/sass/main.scss

- add str replace function
- add import of said function

Sass str_replace function

---

views/pages/components/usage/avatar.blade.php
views/pages/components/usage/avatar/avatar.json
views/pages/components/usage/avatar/icon.blade.php
views/pages/components/usage/avatar/image.blade.php
views/pages/components/usage/avatar/name.blade.php

Move avatar documentation to utilize new usage doc.

Avatar usage doc

---

views/pages/components/molecules/accordion.blade.php
views/pages/components/usage/accordion/accordion.blade.php
views/pages/components/usage/accordion/accordion.json

Move usage example to new usage file structure.

Accordion usage doc

---

views/pages/components/usage/breadcrumb/breadcrumb.blade.php
views/pages/components/usage/breadcrumb/breadcrumb.json

Move usage example to new usage doc file structure

Breadcrumb usage doc

---

views/pages/components/molecules/dropdown.blade.php
views/pages/components/usage/dropdown/click.blade.php
views/pages/components/usage/dropdown/direction.blade.php
views/pages/components/usage/dropdown/dropdown.json
views/pages/components/usage/dropdown/hover.blade.php

Move usage doc to usage dir, add more examples.

Dropdown usage doc

---

views/pages/components/molecules/fileinput.blade.php
views/pages/components/usage/fileinput/fileinput.blade.php
views/pages/components/usage/fileinput/fileinput.json

Move usage example to new usage doc dir.

Fileinput usage doc

---

views/pages/components/molecules/list.blade.php
views/pages/components/usage/listing.blade.php
views/pages/components/usage/listing/listing.blade.php
views/pages/components/usage/listing/listing.json

Move example to new usage dir.

Listing usage doc

---

views/pages/components/molecules/logotype.blade.php
views/pages/components/usage/logotype/logotype.blade.php
views/pages/components/usage/logotype/logotype.json

Move usage example to new usage dir

Logotype usage doc

---

views/pages/components/molecules/modal.blade.php
views/pages/components/usage/modal/modal.blade.php
views/pages/components/usage/modal/modal.json

Move usage example to new usage dir

Modal usage doc

---

views/pages/components/organisms/video.blade.php
views/pages/components/usage/video/video.blade.php
views/pages/components/usage/video/video.json

Move usage example to new usage dir.

Video usage doc

---

views/pages/components/organisms/table.blade.php
views/pages/components/usage/table/table.blade.php
views/pages/components/usage/table/table.json

Move usage example to new usage dir.

Table usage doc

---

views/pages/components/organisms/gallery.blade.php
views/pages/components/usage/gallery/gallery.blade.php
views/pages/components/usage/gallery/gallery.json

Move usage example to new usage dir.

Gallery usage doc

---

views/pages/components/organisms/notice.blade.php
views/pages/components/usage/notice/icon.blade.php
views/pages/components/usage/notice/messageSize.blade.php
views/pages/components/usage/notice/notice.json
views/pages/components/usage/notice/type.blade.php

Move and add usage examples to new usage dir.

Notice usage doc

---

assets/prism/prism.css
source/sass/component/_code.scss
source/sass/component/_paper.scss
source/sass/doc/_generic.scss
source/sass/main.scss
source/sass/setting/_var_colors.scss
source/sass/setting/_var_properties.scss
views/layout/doc.blade.php

- add new design
- altered prism design
- add new toggle design
- removed paper as container

Code Block - Redesign

---

views/pages/components/usage/image/modal.blade.php

- add usage to match new functionality

Image render modal

---

source/sass/component/_grid.scss
source/sass/main.scss
views/pages/components/organisms/grid.blade.php
views/pages/components/usage/grid/container.blade.php
views/pages/components/usage/grid/grid.json
views/pages/components/usage/grid/gutter.blade.php
views/pages/components/usage/grid/item.blade.php

- add grid sass
- add grid docs
- add grid to scss
- remove generic icons

Grid Component

---

views/pages/components/organisms/form.blade.php
views/pages/components/usage/form.blade.php
views/pages/components/usage/form/form.blade.php
views/pages/components/usage/form/form.json

- add form example
- remove old usage file

Form Example

---

views/pages/components/molecules/button.blade.php
views/pages/components/usage/button/button.json
views/pages/components/usage/button/disabled.blade.php
views/pages/components/usage/button/filled.blade.php
views/pages/components/usage/button/icon.blade.php
views/pages/components/usage/button/outlined.blade.php
views/pages/components/usage/button/textWithIcon.blade.php
views/pages/components/usage/button/type.blade.php

- add new name of button styling
- add button type
- add new example for type
- add updated examples

Button Type

---

views/pages/components/usage/card/buttons.blade.php
views/pages/components/usage/card/collapsible.blade.php
views/pages/components/usage/card/dropdown.blade.php
views/pages/components/usage/card/image.blade.php
views/pages/components/usage/card/order.blade.php

- add grid component to prevent overlap in examples

Card Overlap

---

views/docs/utility/radius/radius.json
views/pages/utilities/radius.blade.php

- add new name to border radius util to prevent issues with linux and nav
- add new name to relevant files

Border Radius Rename

---

views/pages/utilities/screen-readers.blade.php

- add better design for documentation

Screen Reader Documentation Design

---

source/php/Navigation.php

- add stricter control if current item is active
- add option to choose to add active state to parents of active item

Navigation Active Items

---

views/pages/utilities/vertical-align.blade.php

- add improved documentation visually

Vertical Align Documentation

---

views/pages/components/usage/fab/fab.blade.php
views/pages/components/usage/fab/fab.json

- add better position for documentation
- add text explaining placement in documentation

FAB Placement

---

source/sass/component/_comment.scss
views/pages/components/usage/comment/comment.blade.php

- add new styling
- add updated usage

Comment author

---

views/pages/script/filter-list.blade.php

- add better design on search box

Filter Documentation

---

views/pages/script/class-toggle.blade.php

- add better example for single toggle
- add example for toggle group

Toggle script improvments

---

views/pages/script/sort.blade.php

- improved design of sorting example

Sorting Example

---

views/layout/script_doc.blade.php

- add better table for attributes

Script Documentation

---

source/sass/main.scss
source/sass/utility/_text-align.scss

- add text align utility
- add utiity to main file

Text Align Utility

---

views/layout/script_doc.blade.php

- add toggle for script code block

Script Code Block

---

views/docs/script/animate/Animate.json
views/docs/script/vertical-align/Vertical-align.json
views/layout/script_doc.blade.php
views/pages/script/animate.blade.php

- remove old json files
- add new layout
- add config files

Animate Documentation

---

source/js/sidebar.js

- add support for single active item that still expands all parents

Sidebar Item Expand

---

source/sass/object/_article.scss

- remove styling on H-elements

Article Stlying

---

views/pages/about/authors.blade.php

Author Cards

---

source/sass/component/_signature.scss
source/sass/main.scss
source/sass/object/_article.scss
views/pages/components/molecules/signature.blade.php
views/pages/components/usage/signature/base.blade.php
views/pages/components/usage/signature/signature.json

- add css file
- add example files
- remove article styling

Signature Component

---

source/sass/component/_card.scss

- add padded to background image

Card Padded

---

source/js/the-datepicker.js
source/sass/component/_date-picker.scss

- add css styling
- remove styling added via js

Date Picker Level

---

views/pages/components/molecules/textarea.blade.php
views/pages/components/usage/textarea/base.blade.php
views/pages/components/usage/textarea/textarea.json

Text Area Documentation

---

source/js/sidebar.js

Sidebar Toggle Bug

---

source/sass/component/_modal.scss

- remove css which gave close button wrong color

Modal Button Color fix

---

index.php
source/js/app.js
source/js/navbar.js
views/pages/components/usage/navbar.blade.php

Add script that dynamically fetches the items needed
in for the current page and renders them in the expanded
navbar by utilizing three data-attributes; url, pageID and pageParentID.

Dynamic navbar

---

source/sass/component/_list.scss
source/sass/main.scss

- add style for items
- add style for links
- add arrow for links

Listing style

---

source/js/app.js
source/js/dynamicSidebar.js
source/js/sidebar.js

Move code that relates to the dynamic version
of the sidebar to it's own class.
Scrap local storage solution.
Fetch children and active items via an endpoint.

Dynamic sidebar rework.

---

source/sass/component/_sidebar.scss

Fixes lineheight if items in sidebars is multiple lines.

Compress sidebar lineheight

---

source/sass/object/_grid.scss

This should be considered a temporary fix. Needs to be work done on html output. Inline modules lack grid classes (and cannot identify if they should be there). Not an easy backend fix, needs to be discussed.

Fix stray column classes css.

---

source/js/app.js
source/js/table.js
source/sass/component/_table.scss

Fix pagination bugs that disabled prev and next incorrectly.
Add background color when hover over a tr.
Fix sort bug.

Fix table component

---

source/sass/component/_typography.scss

CSS Rules for long E-mail addresses

Added email rules

---

source/sass/component/_card.scss

Moved css for icons in card header to styleguide

card header icons

---

source/js/app.js
source/js/keepInViewPort.js
source/js/resizeByChildren.js

Not super happy about this solution.
The arrow at the top in the nav will get a bit off when using this.
To be able to use it without dependency of the nav resize there is a extra js- attribute added.

CU-mhbk6g Add a resize event and viewport correcting code

---

source/sass/component/_segment.scss
views/pages/components/organisms/segment.blade.php
views/pages/components/usage/segment/full-width-card.blade.php
views/pages/components/usage/segment/full-width.blade.php
views/pages/components/usage/segment/reversed.blade.php
views/pages/components/usage/segment/segment.json
views/pages/components/usage/segment/split.blade.php
views/pages/components/usage/segment/stacked.blade.php

Added slot compontents on both full-width and split

Further development on segments

---

source/sass/component/_collection.scss

make collection link style more specific

make collection link style more specific

---

source/sass/component/_slider_item.scss

Restructure css to comply with the new container.

Adds container to slider items.

---

source/sass/object/_grid.scss

Added a modifier for form grids

Add form modifier to adjust spacings

---

source/sass/component/_field.scss
source/sass/component/_select.scss

https://app.clickup.com/t/1m3fjtg

Add styles for fields with suffix

---

source/sass/component/_field.scss
source/sass/component/_option.scss
source/sass/component/_select.scss

Adds styling for invalid vields to field wrapper instead of input

support field validation for input wrappers

---

package-lock.json
package.json
source/js/fields.js
webpack.config.js

Reverts helsingborg-stad/styleguide#444

Revert "Feature/image upload limit"

---

package-lock.json
package.json
source/js/fields.js
webpack.config.js

Reverts helsingborg-stad/styleguide#449

Revert "Revert "Feature/image upload limit""

---

source/sass/component/_button.scss

https://app.clickup.com/t/2z5mnnb

feat: Removed ellipsis and overflow from buttons

---

source/sass/component/_product.scss
views/pages/components/usage/product/product.blade.php

fix: update design

---

source/sass/component/_block.scss
source/sass/component/_field.scss

Allow mobile style to follow desktop ratio

---

source/js/nav.js
source/sass/component/_nav.scss

Fixing adding some padding left for sub ul and breaking words. Setting a static width for the main ul. Making it less "jumpy"

Initial push

---

source/js/form/fileInput.js

Not sure if removing the input does anything useful.

I think this solves the problem

---

assets/data/icons.json
source/js/app.js
source/js/modal.js
source/sass/component/_modal.scss
views/pages/components/usage/modal/modal.blade.php

- `Change` Using `MutationObserver` to init Modal after content has been added to the DOM 
Task is related to and needs to be merged at the same time as https://github.com/helsingborg-stad/Modularity/pull/370

Feature/modal component (connected to work on module curator.io)

---

source/sass/component/_modal.scss
source/sass/component/_segment.scss

Due to segment modal got a positioned wrong

Fix: Modal faulty postion

---

source/sass/component/_image.scss

fix: add blur to lqip images.
